CREATE TABLE IF NOT EXISTS HOTEL (
    ID BIGINT(19) PRIMARY KEY,
    ADDRESS VARCHAR(255),
    DELETED BOOLEAN(1),
    LATITUDE DOUBLE(17),
    LONGITUDE DOUBLE(17),
    NAME VARCHAR(255),
    RATING DOUBLE(17),
    CITY_ID BIGINT(19)
);

CREATE TABLE IF NOT EXISTS CITY (
    ID BIGINT(19) PRIMARY KEY,
    CITY_CENTRE_LATITUDE DOUBLE(17),
    CITY_CENTRE_LONGITUDE DOUBLE(17),
    NAME VARCHAR(255)
);